### PR TITLE
Fix Issue #513

### LINKED ISSUE #513: [Bug] Precompilation Error In Julia 1.11
### Description

```julia
(@v1.11) pkg> precompile BestieTemplate
Precompiling BestieTemplate...
Info Given BestieTemplate was explicitly requested, output will be shown live 
WARNING: Method definition dbg_generate() in module Debug at /home/hzxiaxz/.julia/dev/BestieTemplate/src/debug/helper.jl:68 overwritten at /home/hzxiaxz/.julia/dev/BestieTemplate/src/debug/helper.jl:86.
ERROR: Method overwriting is not permitted during Module precompilation. Use `__precompile__(false)` to opt-out of precompilation.
  ? BestieTemplate
```

### Package Version

0.14.0

### Julia Version

1.11

### Reproduction steps

just add the package

### Relevant log output

_No response_

### Operating System

Linux

### PR DESCRIPTION
**Pull request by hz-xiaxz**
## Related issues
fix #513 

Closes #

## Checklist

- [x] I am following the [contributing guidelines](https://github.com/JuliaBesties/BestieTemplate.jl/blob/main/docs/src/90-contributing.md)
- [x] Tests are passing
- [x] Lint workflow is passing
- [x] Docs were updated and workflow is passing
- [x] [CHANGELOG.md](https://github.com/JuliaBesties/BestieTemplate.jl/blob/main/CHANGELOG.md) was updated

### CODE REVIEW

File: src/debug/helper.jl [hunk 1]
```diff
@@ -83,8 +83,6 @@ function dbg_generate(
   )
 end
 
-dbg_generate(_data = Dict(); kwargs...) = dbg_generate(rand_pkg_name(), _data; kwargs...)
```
Comment (abelsiqueira) [inline src/debug/helper.jl:86]: Maybe it's enough to define

```julia
dbg_generate(_data; kwargs...) = dbg_generate(rand_pkg_name(), _data; kwargs...)
```

Can you try this, please?

File: src/debug/helper.jl [hunk 2]
```diff
@@ -30,7 +30,7 @@ function dbg_data(data_choice, _data = Dict())
     Data.minimum_defaults
   elseif data_choice in [:minimum, :min]
     Data.strategy_minimum
-  elseif data_choice in [:recommended, (:recommended_only):rec, :rec_only]
```
Comment (abelsiqueira) [inline src/debug/helper.jl:33]: Good catch!

**Review by abelsiqueira — CHANGES_REQUESTED** [review]
Thanks a lot for the bug fix!
I've made a suggestion to avoid deleting the second `dbg_generate`.
For the CHANGELOG can you write an entry for the header "### Fixed"?

File: src/debug/helper.jl (hunk 1 above)
Comment (hz-xiaxz) [reply src/debug/helper.jl:86]: This doesn't work either because of lacking type annotation of `_data`. I've found that proper type annotation can avoid this ambiguity, see the new commits.

**Comment by hz-xiaxz** [comment]
I'm not quite sure how to add tests for this fix. Maybe we shall just test all the function calling methods documented works, or just leave them, since it is really simple.

**Review by abelsiqueira — APPROVED** [review]
The new version looks great thanks a lot.
No need to add tests to these functions, as they are just convenience functions used internally for debugging and might change at any time.
This kind of error could have been caught in a different way, though, with something like SnoopCompile, JET, or Aqua (#216, #64) used as linters, but I haven't looked into that yet.
The CHANGELOG entry is also great, thanks

**Comment by abelsiqueira** [comment]
@all-contributors please add @hz-xiaxz for code

**Comment by visr** [comment]
Might be good to tag a release with this PR, because precompilation of the package is broken on the current release:

```
(@v1.11) pkg> precompile
Precompiling project...
  ? BestieTemplate

julia> using BestieTemplate
Precompiling BestieTemplate...
Info Given BestieTemplate was explicitly requested, output will be shown live
WARNING: Method definition dbg_generate() in module Debug at C:\Users\visser_mn\.julia\packages\BestieTemplate\MI8lx\src\debug\helper.jl:68 overwritten at C:\Users\visser_mn\.julia\packages\BestieTemplate\MI8lx\src\debug\helper.jl:86.
ERROR: Method overwriting is not permitted during Module precompilation. Use `__precompile__(false)` to opt-out of precompilation.
  ? BestieTemplate
[ Info: Precompiling BestieTemplate [e5d671a7-4186-4f1a-bf88-c19b630da94f]
WARNING: Method definition dbg_generate() in module Debug at C:\Users\visser_mn\.julia\packages\BestieTemplate\MI8lx\src\debug\helper.jl:68 overwritten at C:\Users\visser_mn\.julia\packages\BestieTemplate\MI8lx\src\debug\helper.jl:86.
ERROR: Method overwriting is not permitted during Module precompilation. Use `__precompile__(false)` to opt-out of precompilation.
┌ Info: Skipping precompilation due to precompilable error. Importing BestieTemplate [e5d671a7-4186-4f1a-bf88-c19b630da94f].
└   exception = Error when precompiling module, potentially caused by a __precompile__(false) declaration in the module.
```

**Comment by abelsiqueira** [comment]
Will do one now

**Comment by abelsiqueira** [comment]
Done
